---

# Homebrew dependencies
dev_homebrew_dependencies:
  - autoconf
  - autogen
  - automake
  - awscli
  - bats
  - boot2docker
  - cmake
  - docker
  - gist
  - git
  - hub
  - jenv
  - jq
  - libtool
  - maven
  - node
  - reattach-to-user-namespace
  - ruby
  - rust
  - sbt
  - scala
  - shellcheck
  - tmux
  - xmlstarlet


# Homebrew Cask dependencies
dev_homebrew_cask_dependencies:
  - cyberduck
  - cornerstone
  - intellij-idea
  - java
  - java6
  - java7
  - slack
  - sourcetree
  - vagrant
  - virtualbox


# Atom packages
atom_packages_packages:
  - atom-beautify
  - atom-lint
  - autocomplete-clang
  - autocomplete-glsl
  - autocomplete-plus
  - compare-files
  - file-icons
  - file-types
  - git-tab-status
  - go-plus
  - hex
  - isotope-ui
  - language-bats
  - language-cmake
  - language-csharp
  - language-d
  - language-diff
  - language-docker
  - language-erlang
  - language-fsharp
  - language-groovy
  - language-haskell
  - language-lisp
  - language-ocaml
  - language-r
  - language-racket
  - language-rust
  - language-scala
  - linter
  - linter-clang
  - linter-js-yaml
  - linter-rust
  - linter-scalac
  - linter-shellcheck
  - linter-xmllint
  - merge-conflicts
  - pretty-json
  - scala-format
  - script
  - seti-syntax
  - seti-ui
  - switch-header-source
  - syntax-settings
  - unity-ui
