---

# Homebrew dependencies
dev_homebrew_dependencies:
  - autoconf
  - autogen
  - automake
  - awscli
  - bats
  - cmake
  - cputhrottle
  - docker
  - docker-compose
  - docker-machine
  - gist
  - git
  - golang
  - hub
  - jenv
  - jq
  - libtool
  - maven
  - node
  - reattach-to-user-namespace
  - ruby
  - rust
  - sbt
  - scala
  - shellcheck
  - tmux
  - xmlstarlet


# Homebrew Cask dependencies
dev_homebrew_cask_dependencies:
  - cyberduck
  - cornerstone
  - intellij-idea
  - java
  - java6
  - java7
  - slack
  - sourcetree
  - vagrant
  - virtualbox


# Atom packages
atom_packages_packages:
  - atom-beautify
  - autocomplete-clang
  - autocomplete-glsl
  - file-icons
  - go-plus
  - hex
  - language-cmake
  - language-docker
  - language-rust
  - language-scala
  - linter
  - linter-clang
  - linter-js-yaml
  - linter-rust
  - linter-scalac
  - linter-shellcheck
  - linter-xmllint
  - merge-conflicts
  - pretty-json
  - scala-format
  - script
  - switch-header-source
