---

# Homebrew dependencies
dev_homebrew_dependencies:
  - autoconf
  - autogen
  - automake
  - awscli
  - bats
  - boot2docker
  - cmake
  - docker
  - gist
  - git
  - hub
  - jenv
  - jq
  - libtool
  - maven
  - node
  - ruby
  - rust
  - sbt
  - scala
  - xmlstarlet


# Homebrew Cask dependencies
dev_homebrew_cask_dependencies:
  - cyberduck
  - cornerstone
  - intellij-idea-ce
  - java
  - java6
  - java7
  - slack
  - sourcetree
  - vagrant
  - virtualbox
