- homebrew: name=bash-completion state=present
- homebrew: name=gnupg state=present
- homebrew: name=keybase state=present
- homebrew_cask: name=1password state=present
- homebrew_cask: name=alfred state=present
- homebrew_cask: name=atom state=present
- homebrew_cask: name=bartender state=present
- homebrew_cask: name=caffeine state=present
- homebrew_cask: name=chromecast state=present
- homebrew_cask: name=cinch state=present
- homebrew_cask: name=dropbox state=present
- homebrew_cask: name=evernote state=present
- homebrew_cask: name=flux state=present
- homebrew_cask: name=google-drive state=present
- homebrew_cask: name=iterm2 state=present
- homebrew_cask: name=keka state=present
- homebrew_cask: name=lunchy state=present
- homebrew_cask: name=music-manager state=present
- homebrew_cask: name=plug state=present
- homebrew_cask: name=radiant-player state=present
- homebrew_cask: name=skype state=present
- homebrew_cask: name=sonos state=present
- homebrew_cask: name=totalfinder state=present
- homebrew_cask: name=vlc state=present
- osx_defaults: domain={{ item.domain }} key={{ item.key }} type={{ item.type }} value={{ item.value }} state={{ item.state }}
  with_items: osx_defaults_values
